### ISSUE TITLE
Initial Maven install build failing

### ISSUE THREAD

**Issue by jphilli22** [browserstack/cucumber-java-browserstack#8]
When attempting to install dependencies after initial cloning, build is failing.

![image](https://user-images.githubusercontent.com/48325402/151835717-0a85c5fe-424b-4835-a9e5-737c0442131e.png)

**Comment by karanshah-browserstack** [comment]
This has been fixed by https://github.com/browserstack/cucumber-java-browserstack/pull/9. Closing this.
